---
title: "Chapter 2 - Small Worlds and Large Worlds"
author: "OG"
date: "7/7/2025"
output: html_document
fig.height: 5

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(glue)
```

## Water Land Proportion - Globe tossing - page 28
Toss the Globe 9 times and note the Water and Land occurences. p is the proportion of Water.
The result is 6 W and 3L.
Evaluation of the posterior with the Grid Method.

```{r grid_eval, eval=TRUE}
# Number of points on the grid
N <- 50
# data
W <- 6
L <- 3
# Prior 
prior <- rep(1, N)
# P(W = 6, L = 3 / p) = dbinom(6, 9, p)
# Probabiliies of the grid
p_grid <- seq(0, 1, length.out = N) 
# Prior x P(W = 6, L = 3 ) for each point of the grid
Posterior_raw <-  dbinom(W, W + L, p_grid)
# Standardisation of posterior
Posterior <-  Posterior_raw/sum(Posterior_raw)
```

```{r, include=TRUE, eval=TRUE}
results <- data.frame(p = p_grid, post = Posterior)
ggplot(results, aes(p, post)) +
  geom_line() +
  labs(title = glue("Posterior for W = {W} and L = {L}"))
```

## Simulating MCMC page 45

```{r, mcmc}
N <- 1000
W <- 6
L <- 3
p <- rep(NA, N)
p[1] <- 0.5

for (i in 2:N) {
  p_new <- rnorm(1, 0.5, 0.1)
  if (p_new < 0 ) p_new <- 1 + p_new
  if (p_new > 1 ) p_new <- 2 - p_new
  q0 <- dbinom(W, W + L, p[i-1])
  q1 <- dbinom(W, W + L, p_new)
  p[i] <- ifelse(runif(1) < q1/q0, p_new, p[i - 1])
}
p_moy <- mean(p)

```

```{r plot_result}
# Plot of chain
ggplot(data.frame(x = 1:N, p = p), aes(x, p)) + 
  geom_line() +
  
  geom_hline(yintercept = p_moy, color = "darkorange")
# Plot of posterior
ggplot(data.frame(x = 1:N, p = p), aes(p)) +
  geom_density() + 
  labs(title = "Post of globe tossing with very simple MCMC")
```


