---
title: "Chapter 4: Geocentric Models"
author: "Olivier Granacher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
```

## 4.1 Normal Distribution

-   Generating a normal distribution from a uniform distribution

```{r generating_gaussian}
norm_distr = replicate(10000, sum(runif(16, -1, 1)))
hist(norm_distr, breaks = 50, main = "Normal Distribution from Uniform Distribution", xlab = "", ylab = "",yaxt = "n")
```

## 4.3 Gaussian Model of height

```{r data_load_Howell1}
d <- read.csv2("data/Howell1.csv", dec = ".")
glimpse(d)
skimr::skim(d)
```

### Prior Predictive

```{r, priors}
# height ~ N(mu, s)
# mu ~ N(178, 20)
# s ~ UNI(, 50)
curve(dnorm(x, 178, 20), from = 120, to = 240, main = "Prior mu ~ dnorm(178, 20)", col = "blue", lwd = 3)
curve(dunif(x, 0, 50), from = -10, to = 60, col = "blue", lwd = 3, main = "s ~ unif(0, 50)")
```

```{r prior posterior}
N <- 1e4
post_prior <-  rnorm(N, mean = rnorm(100, 178, 20), sd = runif(100, 0, 50)) 
hist(post_prior, fill = "lightblue")
```

## 4.4 Linear Model

```{r plot_rel, include=TRUE}
d <- d[d$age>18, ]
plot(d$height ~ d$weight)
```

```{R priors_0}
norm_0_1 <- rnorm(10000)
log_norm <- exp(norm_0_1)
rlnorm <- rlnorm(n = 10000, meanlog = 0, sdlog = 1)
data <- data.frame(norm_0_1, rlnorm, log_norm) |> 
  tidyr::pivot_longer(cols = everything())
ggplot(data, aes(x = value, fill = name)) +
  geom_density(alpha = .4) +
  coord_cartesian(xlim = c(-3, 10))
```

```{r priors, include=TRUE}
# for a normal N(178, 20)
# for b (slope) : lognormal LN(0, 1)
# Plot of lognormal prior
mean_log <- 0
sd_log <- 1
ggplot() +
  xlim(0.1, 10) +
  geom_function(fun = dlnorm,
                args = list(meanlog = mean_log,
                            sdlog = sd_log, 
                            log = F
                ),
                n = 1000
                ) + 
  geom_vline(xintercept = exp(0))

```

```{r prior_slopes, include=TRUE}
prior_a <-  rnorm(50, 100, 15)
prior_b <-  rlnorm(50, 0, 1)
ggplot(data = d, aes(x = weight, y = height)) +
  geom_point(alpha = .3, color = "darkred") +
  geom_abline(intercept = prior_a, slope = prior_b, alpha = .5) + 
  labs(title = "data and priors (slope and intercept")
```

```{r posterior_calculation}
library(brms)
priors <- c(
  prior(normal(100, 15), class = "Intercept"),
  prior(normal(1, 1), class = "b"),
  prior(uniform(0, 50), class = "sigma")
)
brms::make_stancode(
  formula = height~weight,
  data = d,
  prior = priors
)
fit <- brms::brm(
  formula = height~weight,
  data = d,
  #file = "mod_lin_height_weight", # prevents compiling
  cores = 2,
  chains = 4,
  iter = 4000
 # prior = priors
)
sjPlot::tab_model(fit)

# lm for reference
lm_fit <- lm(height~weight, data = d)
sjPlot::tab_model(lm_fit)

```

```{r post_analysis}
posterior_summary(fit) 
```

### Visualize the uncertainty on the average line

```{r draw_fit_posterior}
post <- brms::as_draws_df(fit) 
```

```{r post_uncertainty_interval}
posterior_interval(fit)
```


```{r post_draws}
post = brms::as_draws_df(fit) |> 
    select(starts_with("b_"))
```

```{r table_pred_post}
# Table de prédiction pour chaque ligne du posterior et chaque valeur de weight
## function de prevision
b_int <- mean(post$b_Intercept)
b_slope  <- mean(post$b_weight)
f_height <- function(w = 45.04, b = b_slope, a = b_int) {
  a + b * w
}
## fonction vectorisée
f_height_vec <- function(x, b = post$b_weight, a = post$b_Intercept){
  sapply(x, f_height, b, a)
}
## Création de la table des valeurs
post_result <- sapply(d$weight, FUN = f_height, b = post$b_weight, a = post$b_Intercept)
post_result <- f_height_vec(d$weight, post$b_weight, post$b_Intercept)
# Ajout des colonnes de post
post_result <- cbind(post, post_result)
```

```{r analyse_pred_post}
## Plot ic pour la prédiction
weights_new <- seq(31, 70, 1)
values <- f_height_vec(weights_new)
q_5 <- apply(values, 2, FUN = quantile, 0.05)
q_50 <- apply(values, 2, FUN = quantile, 0.5)
q_95 <- apply(values, 2, FUN = quantile, 0.95)
d_new <- data.frame(
  w = weights_new,
  q_5,
  q_50,
  q_95
)
## Plot ic height
ggplot(d_new, aes(x = w)) +
  geom_ribbon(aes(ymin = q_5, ymax = q_95), alpha = .5) + 
  geom_point(data = d, aes(weight, height))
```

